In [ ]:
#Implementation of different Learning Rules.

In [1]:
#Hebbian Learning Rule
import numpy as np

def hebbian_learning(weights, inputs, outputs, learning_rate):
    for i in range(len(inputs)):
        weights += learning_rate * np.outer(inputs[i], outputs[i])
    return weights

# Example
inputs = np.array([[1, 0], [0, 1], [1, 1]])  # Binary inputs
outputs = np.array([[1, 0], [0, 1], [1, 1]])  # Desired outputs
weights = np.zeros((2, 2))  # Initialize weights
learning_rate = 0.1

weights = hebbian_learning(weights, inputs, outputs, learning_rate)
print("Updated weights (Hebbian):\n", weights)

Updated weights (Hebbian):
 [[0.2 0.1]
 [0.1 0.2]]


In [2]:
#Perceptron Learning Rule
def perceptron_learning(weights, inputs, targets, learning_rate, epochs):
    for epoch in range(epochs):
        for i in range(len(inputs)):
            y = np.where(np.dot(inputs[i], weights) >= 0, 1, 0)
            weights += learning_rate * (targets[i] - y) * inputs[i]
    return weights

# Example
inputs = np.array([[1, 0, 1], [1, 1, 1], [0, 0, 1]])  # Including bias
targets = np.array([1, 1, 0])  # Desired outputs
weights = np.zeros(3)  # Initialize weights (including bias)
learning_rate = 0.1

weights = perceptron_learning(weights, inputs, targets, learning_rate, epochs=10)
print("Updated weights (Perceptron):\n", weights)

Updated weights (Perceptron):
 [ 0.1  0.  -0.1]


In [3]:
#Delta Learning Rule
def delta_learning(weights, inputs, targets, learning_rate, epochs):
    for epoch in range(epochs):
        for i in range(len(inputs)):
            y = np.dot(inputs[i], weights)
            weights += learning_rate * (targets[i] - y) * inputs[i]
    return weights

# Example
inputs = np.array([[1, 0, 1], [1, 1, 1], [0, 0, 1]])  # Including bias
targets = np.array([1, 1, 0])  # Desired outputs
weights = np.zeros(3)  # Initialize weights (including bias)
learning_rate = 0.1

weights = delta_learning(weights, inputs, targets, learning_rate, epochs=10)
print("Updated weights (Delta):\n", weights)

Updated weights (Delta):
 [0.55574086 0.17042858 0.25731795]


In [4]:
#Correlation Learning Rule
def correlation_learning(inputs, targets):
    weights = np.dot(inputs.T, targets)
    return weights

# Example
inputs = np.array([[1, 0], [0, 1], [1, 1]])  # Binary inputs
targets = np.array([[1, 0], [0, 1], [1, 1]])  # Desired outputs

weights = correlation_learning(inputs, targets)
print("Updated weights (Correlation):\n", weights)

Updated weights (Correlation):
 [[2 1]
 [1 2]]


In [5]:
#Out Star Learning Rule
def out_star_learning(weights, target, learning_rate, epochs):
    for epoch in range(epochs):
        weights += learning_rate * (target - weights)
    return weights

# Example
weights = np.array([0.5, 0.5, 0.5])  # Initialize weights
target = np.array([1, 0, 1])  # Desired target
learning_rate = 0.1

weights = out_star_learning(weights, target, learning_rate, epochs=10)
print("Updated weights (Out Star):\n", weights)

Updated weights (Out Star):
 [0.82566078 0.17433922 0.82566078]


In [6]:
#Competitive Learning Rule
def competitive_learning(weights, inputs, learning_rate, epochs):
    for epoch in range(epochs):
        for x in inputs:
            # Find the winning neuron (closest weight vector)
            distances = np.linalg.norm(weights - x, axis=1)
            winner = np.argmin(distances)
            # Update the weights of the winning neuron
            weights[winner] += learning_rate * (x - weights[winner])
    return weights

# Example
inputs = np.array([[1, 0], [0, 1], [1, 1]])  # Input patterns
weights = np.random.rand(3, 2)  # Initialize weights for 3 neurons
learning_rate = 0.1

weights = competitive_learning(weights, inputs, learning_rate, epochs=10)
print("Updated weights (Competitive):\n", weights)

Updated weights (Competitive):
 [[0.19042335 0.86934441]
 [0.31678685 0.14154423]
 [0.98353168 0.52502298]]
